---
# Task to configure fwupd update-motd script

- name: "set_fwupd | Deploy fwupd update-motd script"
  ansible.builtin.template:
    src: 85-fwupd.j2
    dest: /etc/update-motd.d/85-fwupd.j2
    mode: '0755'
    owner: root
    group: root
